# Generated by Django 5.2.4 on 2025-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(
                help_text="Pisahkan setiap teknologi dengan koma, contoh: Python, Django, HTML",
                max_length=200,
            ),
        ),
    ]
